name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      distro:
        description: 'Distro name'
        required: true
        type: choice
        options:
        - centos7
        - centos6

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # s2technologies/build-base

jobs:
  push_to_registry:
    name: Push Docker image to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./${{ github.event.inputs.distro }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.distro }}
